name: Auto Commit Changes

on:
  push:
    branches:
      - master

jobs:
  commit-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make changes (example step)
      run: |
        echo "New change at $(date)" >> travel-blog.txt

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update travel blog automatically" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push
    
